lotr/urls.py
from django.conf.urls.defaults import *
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, ListView, UpdateView, CreateView, DeleteView, TemplateView
from django.db.models import Count
from sssd.lotr.models import *
from sssd.lotr.views import *

urlpatterns = patterns('',
	url(r'^$', TodayEvent.as_view(), name='lotr-home'),
	url(r'^noresults/', TemplateView.as_view(template_name = 'lotr/base_noresults.html'), name='no-results'),
	url(r'^event/(?P<pk>\d+)/$', EventView.as_view(), name='event-view'),
	url(r'^event/month/(?P<month>\d+)/', EventByMonth.as_view(), name='event-month-view'),
	url(r'^event/date/(?P<month>\d+)/(?P<day>\d+)/$', EventByDate.as_view(), name='event-date-view'),
	url(r'^journey/(?P<pk>\d+)/$', JourneyView.as_view(), name='journey-view'),
)

urls.py
from django.conf.urls.defaults import *
from django.views.generic import DetailView, ListView, UpdateView, CreateView, DeleteView
from django.contrib import admin
from sssd.somesmart.models import *
from sssd.somesmart.views import *

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^admin/', include(admin.site.urls)),
	url(r'^adventure/', include('sssd.adventure.urls')),
	url(r'^lotr/', include('sssd.lotr.urls')),
	url(r'^', include('sssd.somesmart.urls')),
)

lotr/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
import os

class Location(models.Model):
	name = models.CharField(max_length=100)
	x_position = models.DecimalField(max_digits=15, decimal_places=9, default=0)
	y_postion = models.DecimalField(max_digits=15, decimal_places=9, default=0)

	def __unicode__(self):
		return self.name

class Journey(models.Model):
	short_description = models.CharField(max_length=250)
	long_description = models.TextField()
	start_location = models.ForeignKey(Location, related_name='journey_start')
	end_location = models.ForeignKey(Location, related_name='journey_end')

	def __unicode__(self):
		return self.short_description

class Character(models.Model):
	first_name = models.CharField(max_length=100, blank=True)
	last_name = models.CharField(max_length=100, blank=True)

	def __unicode__(self):
		return u"%s %s" % (self.first_name, self.last_name)

class Event(models.Model):

	DAY_OF_WEEK = (
		(1, 'Sunday'),
		(2, 'Monday'),
		(3, 'Tuesday'),
		(4, 'Wednesday'),
		(5, 'Thursday'),
		(6, 'Friday'),
		(7, 'Saturday'),
	)

	EVENT_MONTH = (
		(1, 'January'),
		(2, 'February'),
		(3, 'March'),
		(4, 'April'),
		(5, 'May'),
		(6, 'June'),
		(7, 'July'),
		(8, 'August'),
		(9, 'September'),
		(10, 'October'),
		(11, 'November'),
		(12, 'December'),
	)

	event_month = models.IntegerField(choices=EVENT_MONTH)
	event_day = models.IntegerField()
	shire_year = models.IntegerField()
	third_age_year = models.IntegerField()
	explicit = models.BooleanField()
	deck = models.CharField(max_length=250)
	description = models.TextField()
	week_day = models.IntegerField(choices=DAY_OF_WEEK)
	group_size = models.IntegerField()
	x_position = models.DecimalField(max_digits=15, decimal_places=9, default=0)
	y_postion = models.DecimalField(max_digits=15, decimal_places=9, default=0)
	journey = models.ForeignKey(Journey)

	def __unicode__(self):
		return self.deck

class CharacterEvent(models.Model):
	event = models.ForeignKey(Event)
	character =	models.ForeignKey(Character)

lotr/views.py
from django.shortcuts import get_object_or_404, render_to_response, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.db.models import Q, Count, Sum
from django.views.generic import DetailView, ListView, UpdateView, CreateView, FormView
from django.core.urlresolvers import reverse
from django.template import RequestContext
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator
from django.template.defaultfilters import slugify
from sssd.lotr.models import *
from decimal import *
from datetime import datetime

def get_dates(month, day):
	day = int(day)
	month = int(month)
	prev_day = day - 1
	next_day = day + 1
	prev_month = month
	next_month = month
	if day == 30:
		next_day = 1
		if month == 12:
			next_month = 1
		else:
			next_month = month + 1
	if day == 1:
		prev_day = 30
		if month == 1:
			prev_month = 12
		else:
			prev_month = month - 1
	dates = {'prev_month': prev_month, 'next_month': next_month, 'prev_day': prev_day, 'next_day': next_day}
	return dates

def get_month_dates(month):
	month = int(month)
	prev_month = month - 1
	next_month = month + 1
	if month == 1:
		prev_month = 12
	if month == 12:
		next_month = 1
	dates = {'prev_month': prev_month, 'next_month': next_month}
	return dates

class TodayEvent(ListView):
	template_name='lotr/base_index.html'
	context_object_name = 'event_list'

	def get_queryset(self):
		self.tdy = datetime.now().date()
		return Event.objects.select_related().filter(event_day=self.tdy.day, event_month=self.tdy.month)

	def get_context_data(self, **kwargs):
		context = super(TodayEvent, self).get_context_data(**kwargs)
		self.tdy = datetime.now().date()
		self.dates = get_dates(self.tdy.month, self.tdy.day)
		context ['dates'] = self.dates
		return context

class EventView(DetailView):
	queryset = Event.objects.select_related()
	template_name='lotr/base_event.html'
	context_object_name = 'event_detail'

	def get_context_data(self, **kwargs):
		context = super(EventView, self).get_context_data(**kwargs)
		self.event = Event.objects.get(pk=self.kwargs['pk'])
		self.dates = get_dates(self.event.event_month, self.event.event_day)
		context ['dates'] = self.dates
		return context

class EventByDate(ListView):
	template_name = 'lotr/base_event_by_date.html'
	context_object_name = 'event_list'

	def get_queryset(self):
		return Event.objects.select_related().filter(event_day=self.kwargs['day'], event_month=self.kwargs['month']).order_by('shire_year')

	def get_context_data(self, **kwargs):
		context = super(EventByDate, self).get_context_data(**kwargs)
		self.dates = get_dates(self.kwargs['month'], self.kwargs['day'])
		context ['dates'] = self.dates
		if self.kwargs['day'] == '31':
			context ['na'] = {'value': '<p>Unfortunately the 31st does not exist in the Shire calendar. Please try a different date.</p>'}
		return context

class EventByMonth(ListView):
	template_name = 'lotr/base_event_month.html'
	context_object_name = 'event_list'

	def get_queryset(self):
		return Event.objects.select_related().filter(event_month=self.kwargs['month']).order_by('event_day', 'shire_year')

	def get_context_data(self, **kwargs):
		context = super(EventByMonth, self).get_context_data(**kwargs)
		self.dates = get_month_dates(self.kwargs['month'])
		context ['dates'] = self.dates
		return context		

class JourneyView(DetailView):
	queryset = Journey.objects.select_related()
	template_name='lotr/base_journey.html'
	context_object_name = 'journey'

templates/lotr/base_event.html
{% extends "somesmart/base.html" %}
{% load humanize %}
{% block title %}{{ event_detail.journey }}{% endblock title %}
{% block top-content %}{% endblock %}
{% block content %}
<div><a class="btn btn-default" href="{% url 'event-date-view' event_detail.event_month event_detail.event_day %}">More from {{ event_detail.get_event_month_display }} {{ event_detail.event_day|ordinal }}</a>{% include "lotr/include_today_link.html" %}</div>
<br>
<div>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h4>{{ event_detail.deck }}<br><small> <a href="{% url 'journey-view' event_detail.journey.id %}">{{ event_detail.journey }}</a></small></h4>
		</div>
		<div class="panel-body">
			<p>{{ event_detail.description }}</p>
			{% with event_detail as event %}
			{% include "lotr/include_characters_present.html" %}
			{% endwith %}
		</div>
	</div>
</div>
<br>
{% include "lotr/include_day_nav.html" %}
{% endblock content %}
{% block top-right-content %}{% endblock %}
{% block right-content %}
	{% include "lotr/include_month_warning.html" %}
	{% include "somesmart/include_contact.html" %}
	{% include "lotr/include_search_form.html" %}
{% endblock %}
{% block app.scripts %}
<script type="text/javascript" src="{{ MEDIA_URL }}lotr/functions.js"></script>
{% endblock %}

templates/lotr/base_event_by_date.html
{% extends "somesmart/base.html" %}
{% load humanize %}
{% block title %}The Lord of the Rings Calendar{% endblock title %}
{% block top-content %}{% endblock %}
{% block content %}
{% include "lotr/include_today_link.html" %}
<div class="row">
	<h3>{% for event in event_list %}{% if forloop.counter == 1 %}<a href="{% url 'event-month-view' event.event_month %}">{{ event.get_event_month_display }}</a> {{ event.event_day|ordinal }}{% endif %} in{% endfor %} <strong>The Lord of the Rings</strong></h3>
	{% include "lotr/include_event_list.html" %}
</div>
{% endblock content %}
{% block top-right-content %}{% endblock %}
{% block right-content %}
	{% include "lotr/include_month_warning.html" %}
	{% include "somesmart/include_contact.html" %}
	{% include "lotr/include_search_form.html" %}
{% endblock %}
{% block app.scripts %}
<script type="text/javascript" src="{{ MEDIA_URL }}lotr/functions.js"></script>
{% endblock %}

templates/lotr/base_event_month.html
{% extends "somesmart/base.html" %}
{% load somesmart_extras %}
{% block title %}The Lord of the Rings Calendar{% endblock title %}
{% block top-content %}{% endblock %}
{% block content %}
<p class="well well-sm">Because the events of <strong>The Lord of the Rings</strong> span multiple years the position of the days in the calendar below should not be used to assume a day of the week.</p>
<br>
<div class="row">{% include "lotr/include_today_link.html" %}</div>
<br>
<div class="row">
	{% regroup event_list by event_day as day_list %}
	<div>
		{% for day in day_list %}
			{% if forloop.counter == 1 %}
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4>{% for event in day.list %}{% if forloop.counter == 1 %}{{ event.get_event_month_display }}{% endif %}{% endfor %} in <strong>The Lord of the Rings</strong></h4>
				</div>
				<table class="table calendar">
					<tr>
			{% endif %}
					<td class="calendar"><span class="pull-right">{{ day.grouper }}</span><br>{% for event in day.list %}{% with event.deck|length|add:-1 as deck_len %}<p><a href="{% url 'event-date-view' event.event_month event.event_day %}" title="{{ event.deck }}">{% if deck_len > 50 %}{{ event.deck|truncchar:50 }}...{% else %}{{ event.deck }}{% endif %}</a></p>{% endwith %}{% endfor %}</td>
				{% if forloop.counter|divisibleby:"7" %}</tr><tr>{% endif %}
				{% if forloop.last %}
				</tr>
				</table>
			</div>
			{% endif %}
		{% empty %}
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4>No events!</h4>
				</div>
				<div class="panel-body">
					<p>Nothing seems to have happened in this month... (or more likely it's not in the database yet)</p>
				</div>
			</div>
		{% endfor %}
	</div>
	{% for day in day_list %}
		{% if forloop.counter == 1 %}
			<div>
				<div class="pull-left">
					<a class="btn btn-success" href="/lotr/event/month/{{ dates.prev_month }}/"><i class="glyphicon glyphicon-chevron-left"></i> Previous Month</a>
				</div>	
				<div class="pull-right">
					<a class="btn btn-success" href="/lotr/event/month/{{ dates.next_month }}/">Next Month <i class="glyphicon glyphicon-chevron-right"></i></a>
				</div>
			</div>
		{% endif %}
	{% endfor %}
</div>
{% endblock content %}
{% block top-right-content %}{% endblock %}
{% block right-content %}
	{% include "lotr/include_month_warning.html" %}
	{% include "somesmart/include_contact.html" %}
	{% include "lotr/include_search_form.html" %}
{% endblock %}
{% block app.scripts %}
<script type="text/javascript" src="{{ MEDIA_URL }}lotr/functions.js"></script>
{% endblock %}

templates/lotr/base_index.html
{% extends "somesmart/base.html" %}
{% block title %}Welcome to the Lord of the Rings Calendar!{% endblock title %}
{% block content %}
<p class="well well-sm">Like everyone at some point or another, I've often wondered "what happened on my birthday in <strong>The Lord of the Rings</strong>?" This, naturally, expanded into the idea that I should provide a simple way for everyone to find this information. Currently, I only have data from 9/20 to 3/2 loaded, but hopefully I'll get to the rest eventually. If you notice any errors, let me know!</p>
<div>
	<h3>Today in <strong>The Lord of the Rings</strong>:</h3>
	{% include "lotr/include_event_list.html" %}
</div>
<div>
{% include "lotr/include_search_form.html" %}
</div>
{% endblock content %}
{% block top-right-content %}{% endblock top-right-content %}
{% block right-content %}
	<div class="col-md-10 col-lg-offset-1">
		{% include "lotr/include_month_warning.html" %}
		{% include "somesmart/include_contact.html" %}
	</div>
{% endblock %}
{% block app.scripts %}
<script type="text/javascript" src="{{ MEDIA_URL }}lotr/functions.js"></script>
{% endblock %}

templates/lotr/base_journey.html
{% extends "somesmart/base.html" %}
{% load humanize %}
{% block title %}{{ journey }}{% endblock title %}
{% block content %}
<div class="row">{% include "lotr/include_today_link.html" %}</div>
<br>
<div class="row">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3>{{ journey }}</h3>
		</div>
		<div class="panel-body">
			<dl class="list-unstyled">
				{% for event in journey.event_set.all %}
					<dt>{{ event.get_event_month_display }} {{ event.event_day|ordinal }}</dt><dd><a href="{% url 'event-view' event.id %}">{{ event.deck }}</a></dd>
				{% endfor %}
			</dl>
		</div>
	</div>
</div>
{% endblock content %}
{% block top-right-content %}{% endblock top-right-content %}
{% block right-content %}
	<div class="col-md-10 col-lg-offset-1">
		{% include "lotr/include_month_warning.html" %}
		{% include "somesmart/include_contact.html" %}
		{% include "lotr/include_search_form.html" %}
	</div>
{% endblock %}
{% block app.scripts %}
<script type="text/javascript" src="{{ MEDIA_URL }}lotr/functions.js"></script>
{% endblock %}

templates/lotr/base_noresults.html
{% extends "somesmart/base.html" %}
{% block top-content %}{% endblock %}
{% block content %}
<p class="alert alert-info">It appears you didn't enter a valid value. Please return to the previous page and try again. If you continue to receive this message, please <a href="/contact/">contact us</a>.</p>
{% endblock %}
{% block top-right-content %}{% endblock top-right-content %}
{% block right-content %}
	<div class="col-md-10 col-lg-offset-1">
		{% include "lotr/include_month_warning.html" %}
		{% include "somesmart/include_contact.html" %}
		{% include "lotr/include_search_form.html" %}
	</div>
{% endblock %}

templates/lotr/include_characters_present.html
<p>These major characters were present</p>
	<ul class="list-unstyled review">
		{% for character in event.characterevent_set.all %}
			<li>{{ character.character }}</li>
		{% endfor %}
	</ul>

templates/lotr/include_day_nav.html
<div>
	<div class="pull-left">
		<a class="btn btn-success" href="/lotr/event/date/{{ dates.prev_month }}/{{ dates.prev_day }}/"><i class="glyphicon glyphicon-chevron-left"></i> Previous Day</a>
	</div>	
	<div class="pull-right">
		<a class="btn btn-success" href="/lotr/event/date/{{ dates.next_month }}/{{ dates.next_day }}/">Next Day <i class="glyphicon glyphicon-chevron-right"></i></a>
	</div>
</div>

templates/lotr/include_event_list.html
<div>
	{% for event in event_list %}
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4>{{ event.third_age_year }} (3rd Age) - <a href="{% url 'journey-view' event.journey.id %}">{{ event.journey }}</h4>
			</div>
			<div class="panel-body">
				<strong><p><a href="{% url 'event-view' event.id %}">{{ event.deck }}</a></p></strong>
				<p>{{ event.description }}</p>
				{% include "lotr/include_characters_present.html" %}
			</div>
		</div>
	{% empty %}
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4>No events!</h4>
			</div>
			<div class="panel-body">
				{% if na %}
					{{ na.value|safe }}
				{% else %}
					<p>Nothing seems to have happened on this day... (or more likely it's not in the database yet)</p>
				{% endif %}
			</div>
		</div>
	{% endfor %}
</div>
{% for event_detail in event_list %}
	{% if forloop.counter == 1 %}
		{% include "lotr/include_day_nav.html" %}
	{% endif %}
{% endfor %}

templates/lotr/include_month_warning.html
<p class="alert alert-danger">In the calendar of the Shire, there are 12 months each with 30 days, so there will be no results for the 31st of any month, and February will have entries on the 29th and 30th.</p>

templates/lotr/include_search_form.html
<h4>Find the events from a specific day</h4>
<form class="form" id="date-form" action="" method="post">
	<table class="table table-striped">
		<tr>
			<td><label>Month: </label></td>
			<td><select name="month" id="month" class="form-control">
					<option value="1">January</option>
					<option value="2">February</option>
					<option value="3">March</option>
					<option value="4">April</option>
					<option value="5">May</option>
					<option value="6">June</option>
					<option value="7">July</option>
					<option value="8">August</option>
					<option value="9">September</option>
					<option value="10">October</option>
					<option value="11">November</option>
					<option value="12">December</option>
				</select>
			</td>
		</tr>
		<tr>
			<td><label>Day: </label></td>
			<td><select name="day" id="day" class="form-control">
					<option value="1">1</option>
					<option value="2">2</option>
					<option value="3">3</option>
					<option value="4">4</option>
					<option value="5">5</option>
					<option value="6">6</option>
					<option value="7">7</option>
					<option value="8">8</option>
					<option value="9">9</option>
					<option value="10">10</option>
					<option value="11">11</option>
					<option value="12">12</option>
					<option value="13">13</option>
					<option value="14">14</option>
					<option value="15">15</option>
					<option value="16">16</option>
					<option value="17">17</option>
					<option value="18">18</option>
					<option value="19">19</option>
					<option value="20">20</option>
					<option value="21">21</option>
					<option value="22">22</option>
					<option value="23">23</option>
					<option value="24">24</option>
					<option value="25">25</option>
					<option value="26">26</option>
					<option value="27">27</option>
					<option value="28">28</option>
					<option value="29">29</option>
					<option value="30">30</option>
				</select>
			</td>
		</tr>
	</table>
</form>
<a href="/lotr/event/date/1/1/" class="btn btn-success pull-right" id="event-url">See Events</a>

templates/lotr/include_today_link.html
<a href="/lotr/" class='btn btn-default pull-right'>Back to Today</a>