urls.py
from django.conf.urls.defaults import *
from django.views.generic import DetailView, ListView, UpdateView, CreateView, DeleteView
from django.contrib import admin
from sssd.somesmart.models import *
from sssd.somesmart.views import *

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^admin/', include(admin.site.urls)),
	url(r'^adventure/', include('sssd.adventure.urls')),
	url(r'^lotr/', include('sssd.lotr.urls')),
	url(r'^', include('sssd.somesmart.urls')),
)

somesmart/models.py
from django.db import models
from django.core.urlresolvers import reverse
import datetime
from django.contrib.auth.models import User
import os
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill, Adjust
import tagging

class IntegerRangeField(models.IntegerField):
	def __init__(self, verbose_name=None, name=None, min_value=None, max_value=None, **kwargs):
		self.min_value, self.max_value = min_value, max_value
		models.IntegerField.__init__(self, verbose_name, name, **kwargs)
	def formfield(self, **kwargs):
		defaults = {'min_value': self.min_value, 'max_value':self.max_value}
		defaults.update(kwargs)
		return super(IntegerRangeField, self).formfield(**defaults)

class Genre(models.Model):
	name = models.TextField(max_length=100)
	slug = models.SlugField()

	def __unicode__(self):
		return self.name

	def save(self, *args, **kwargs):
		if not self.id:
			# Newly created object, so set slug
			self.slug = slugify(self.name)

		super(Genre, self).save(*args, **kwargs)

class Author(models.Model):
	last_name = models.CharField(max_length=200)
	first_name = models.CharField(max_length=200)
	birth_date = models.DateTimeField(null=True, default=None, blank=True)
	death_date = models.DateTimeField(null=True, default=None, blank=True)
	pen_name = models.BooleanField()
	parent_author = models.ForeignKey('self', blank=True, default=None, null=True, help_text='The real name of a pen name')

	def __unicode__(self):
		return u"%s %s" % (self.first_name, self.last_name)	

class Book(models.Model):
	title = models.CharField(max_length=200)
	author = models.ForeignKey(Author)
	original_publication = models.DateTimeField()
	synopsis = models.TextField(blank=True)
	reading_age = models.IntegerField()
	content_advisory = models.TextField(blank=True)
	genre = models.ForeignKey(Genre)

	def __unicode__(self):
		return self.title

tagging.register(Book)

class Edition(models.Model):
	def get_image_path(instance, filename):
		return os.path.join('photos/book', str(instance.book.id), filename)

	FORMAT = (
		(1, 'Hardcover'),
		(2, 'Paperback'),
		(3, 'Digital'),
		(4, 'Audio'),
	)

	book = models.ForeignKey(Book)
	isbn = models.CharField(max_length=20)
	published = models.DateTimeField()
	pages = models.IntegerField()
	format = models.IntegerField(choices=FORMAT)
	cover = models.ImageField(upload_to=get_image_path, blank=True)
	cover_thumbnail = ImageSpecField([Adjust(contrast=1.2, sharpness=1.1), ResizeToFill(50, 50)], image_field='cover', format='JPEG', options={'quality': 90})
	cover_large = ImageSpecField([Adjust(contrast=1.2, sharpness=1.1), ResizeToFill(333, 500)], image_field='cover', format='JPEG', options={'quality': 90})
	cover_md = ImageSpecField([Adjust(contrast=1.2, sharpness=1.1), ResizeToFill(100, 170)], image_field='cover', format='JPEG', options={'quality': 90})

	def __unicode__(self):
		return u"%s - %s" % (self.book.title, self.get_format_display())

class Review(models.Model):
	reader = models.ForeignKey(User, related_name="+")
	started = models.DateTimeField()
	finished = models.DateTimeField()
	edition = models.ForeignKey(Edition)
	critique = models.TextField(blank=True)
	one_sentence = models.CharField(max_length=300, null=True, default=None, blank=True)
	recommend = models.BooleanField()

	def __unicode__(self):
		return self.one_sentence

#I should consider doing this as a tagging module of some sort. The advantage of having it being "keywords" like this
#is we can also attribute the tag/keyword to the user.
class Keyword(models.Model):
	book = models.ForeignKey(Book)
	reader = models.ForeignKey(User, related_name='+')
	keyword = models.CharField(max_length=100)

class QuoteType(models.Model):
	name = models.CharField(max_length=50)
	def __unicode__(self):
		return self.name

class Quote(models.Model):
	edition = models.ForeignKey(Edition)
	reader = models.ForeignKey(User, related_name='+')
	quote_type = models.ForeignKey(QuoteType)
	quote = models.TextField()
	page = models.IntegerField()

	def __unicode__(self):
		return self.quote

class Note(models.Model):
	quote = models.ForeignKey(Quote)
	reader = models.ForeignKey(User, related_name='+')
	note = models.TextField()

	def __unicode__(self):
		return self.note

class Radar(models.Model):
	book = models.ForeignKey(Book)
	maturity = models.IntegerField()
	violence = models.IntegerField()
	action = models.IntegerField()
	epic = models.IntegerField()
	world = models.IntegerField()
	realism = models.IntegerField()
	modernity = models.IntegerField()
	humor = models.IntegerField()

class Shelf(models.Model):
	reader = models.ForeignKey(User, related_name='+')
	name = models.CharField(max_length=100)
	private = models.BooleanField()

	def __unicode__(self):
		return self.name

class ShelfDetail(models.Model):
	shelf = models.ForeignKey(Shelf)
	book = models.ForeignKey(Book)

#will probably be able to do this just by pulling in the current status from goodreads
class Currently(models.Model):
	edition = models.ForeignKey(Edition)
	reader = models.ForeignKey(User, related_name='+')
	page = models.IntegerField()

class Favorite(models.Model):
	book = models.ForeignKey(Book)
	user = models.ForeignKey(User, related_name='+')
	rank = models.IntegerField()
	comment = models.TextField()

# ************************************************************** #
# ************************ list data *************************** #
# ************************************************************** #

class List(models.Model):
	list_name = models.CharField(max_length=200)
	list_descr = models.CharField(max_length=200)
	user = models.ForeignKey(User, related_name="+") #this is the person who created it, and it will always be here
	def __unicode__(self):
		return self.list_name
		return u"%s - %s" % (self.list_name, self.list_descr)
	def get_absolute_url(self):
		return "/list/%i/" % self.id
	def get_edit_url(self):
		return "/edit/list/%i/" % self.id
	def get_delete_url(self):
		return "/delete/list/%i/" % self.id	
	def get_add_url(self):
		return "/add/list/"

class ListDetail(models.Model):
	list = models.ForeignKey(List, related_name="list_details")
	book = models.ForeignKey(Book)

# ************************************************************** #
# *********************** series data ************************** #
# ************************************************************** #

class Series(models.Model):
	name = models.CharField(max_length=200)
	count = models.IntegerField()

	def __unicode__(self):
		return self.name

class SeriesDetail(models.Model):
	series = models.ForeignKey(Series)
	book = models.ForeignKey(Book)
	sequence = models.IntegerField()

	def __unicode__(self):
		return u"%s - %s, %s of %s" % (self.series, self.book, self.sequence, self.series.count)

templates/todo/add_external_task.html
{% extends "todo/base.html" %}
{% block page_heading %}{% endblock %}
{% block title %}File Ticket{% endblock %}
<a class="btn btn-default" href="/todo/">To-Do Home</a>
{% block content %}
{% if perms.todo.add_list %}
{% if messages %}
<ul class="messages">
	{% for message in messages %}
	<li>{{ message }}</li>
	{% endfor %}
</ul>
{% endif %}
<h2>{{ task }}</h2>
<form class="form-horizontal" action="" method="POST">
{% csrf_token %}	
{% if task.note %}
<div class="task_note"><strong>Note:</strong> {{ task.note|safe|urlize|linebreaks }}</div>
{% endif %}
<div id="TaskEdit">
<h3>File Trouble Ticket</h3>
<p>Trouble with a computer or other technical system at the J-School? <br />
Use this form to report the difficulty - we'll get right back to you. </p>
{% if form.errors %}
	{% for error in form.errors %}
	<ul class="errorlist">
		<li><strong>The {{ error|escape }} field is required.</strong></li>
	</ul>
	{% endfor %}
<br />
{% endif %}
<table class="table table-striped table-hover table-todo">
	{{ form.management_form }}
	{{ form.id }}
<tr>
	<td>Summary:</td>
	<td>{{ form.title }} <br />
	Include the workstation number in your summary, e.g. <br />
	"Radio Lab # 4: Purple smoke pouring out the back."
	 </td>
</tr>
<tr>
	<td valign="top">Note:</td>
	<td valign="top">{{ form.note }}<br />
	Please describe the problem.   </td>
</tr>
<tr>
	<td>Priority:</td>
	<td>{{ form.priority }} <br />
	Enter a number between 1 and 5, <br />
	where 5 is highest ("Computer is on fire = True").
	 </td>
</tr>
</table>
<p><input type="submit" class="btn btn-default" name="add_task" value="Submit"></p>
</div>
</form>
{% endif %}
{% endblock %}

templates/todo/add_list.html
{% extends "todo/base.html" %}
{% block page_heading %}{% endblock %}
{% block title %}Add Todo List{% endblock %}
<a class="btn btn-default" href="/todo/">To-Do Home</a>
{% block content %}
{% if perms.todo.add_list %}
{% if messages %}
<ul class="messages">
	{% for message in messages %}
	<li>{{ message }}</li>
	{% endfor %}
</ul>
{% endif %}
<h2>Add a list:</h2>
<form class="form-horizontal" action="" method="post">
	{% csrf_token %}
<table class="table table-striped table-hover table-todo">{{ form.as_table }}</table>
<p><input type="submit" value="Submit" class="btn btn-default"></p>
</form>
{% endif %}
{% endblock %}

templates/todo/base.html
{% extends "somesmart/base.html" %}
{% block page_heading %}GTD (Getting Things Done){% endblock %}
{% block extrahead %}
<!-- CSS and JavaScript for django-todo -->
<!--<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}todo/styles.css" /> -->
<script src="{{STATIC_URL}}js/ui.datepicker.js" type="text/javascript"></script>
<script src="{{STATIC_URL}}js/jquery.tablednd_0_5.js" type="text/javascript"></script> 
<script type="text/javascript" charset="utf-8">
	// thedate.x comes from the edit_task view. If this is a new entry, 
	// thedate won't be present and datepicker will fall back on the default (today).
	$(document).ready(function(){
		$('#id_due_date').datepicker({defaultDate: new Date({{thedate.year}}, {{thedate.month}} - 1, {{thedate.day}}),});
	});
</script>
{% endblock extrahead %}
{% block top-right-content %}{% endblock %}

templates/todo/del_list.html
{% extends "somesmart/base.html" %}
{% block title %}{{ list_title }} to-do items{% endblock %}
{% block content %}
{% if perms.todo.add_list %}
{# Only admins can delete lists. #}
{% ifequal can_del 1 %}
	{% if list_killed %}
		<p> {{ list.name }} is gone.</p>
		<a href="{% url 'todo-lists' %}">Return to lists</a>
	{% else %}
		<h1>Delete entire list: {{ list.name }} ?</h1>
		<p>Category tally:</p>
		<ul>
			<li>Incomplete: {{ item_count_undone }} </li>
			<li>Complete: {{ item_count_done }} </li>
			<li><strong>Total: {{ item_count_total }}</strong> </li>
		</ul>
		<p> ... all of which will be irretrievably <strong>blown away</strong>. Are you sure you want to do that?</p>
		<form action="" method="post" accept-charset="utf-8" class="form-horizontal">
		{% csrf_token %}
			<input type="hidden" name="list" value="{{ list.id }}" id="some_name">
		<p><input type="submit" name="delete-confirm" value="Do it! &rarr;" class="btn btn-default"> </p>
		</form>
		<a href="{% url 'todo-incomplete_tasks' list.id list_slug %}">Return to list: {{ list.name }}</a>
	{% endif %}
{% else %}
	<p>Sorry, you don't have permission to delete lists. Please contact your group administrator.</p>
{% endifequal %}
{% endif %}
{% endblock %}

templates/todo/list_lists.html
{% extends "todo/base.html" %}
{% block title %}{{ list_title }} Todo Lists{% endblock %}
{% block content %}
{% if perms.todo.add_list %}
	{% if messages %}
	<ul class="messages">
		{% for message in messages %}
		<li>{{ message }}</li>
		{% endfor %}
	</ul>
	{% endif %}
	<h1>To-do Lists</h1>
	<p>{{ item_count }} items in {{ list_count }} lists</p>
	{% regroup list_list by group as section_list %}
	{% for group in section_list %}
		<h3>{{ group.grouper }}</h3>
		<ul>
			{% for item in group.list %}
				<li><a class="todo" href="{% url 'todo-incomplete_tasks' item.id item.slug %}">{{ item.name }} </a> ({{ item.incomplete_tasks.count }}/{{ item.item_set.count }})</li>
			{% endfor %}
		</ul>
	{% endfor %}
	<div class="todo-break">
	&nbsp;
	</div>
	<p><a class="btn btn-default" href="{% url 'todo-add_list' %}">Create new todo list</a></p>
{% endif %}
{% endblock %}

templates/todo/search_results.html
{% extends "todo/base.html" %}
{% block title %}Search results{% endblock %}
{% block body_id %}post_search{% endblock %}
{% block content_title %}
	<h2 class="page_title">Search</h2>
{% endblock %}
{% block content %}
{% if perms.todo.add_list %}
	{% if message %}
	<p class="message">{{ message }}</p>
	{% endif %}
	{% if found_items %}
	<h2>{{found_items.count}} search results for term: "{{ query_string }}"</h2>
	<div class="post_list">
	{% for f in found_items %}
	<p><strong><a href="{% url 'todo-task_detail' f.id %}">{{ f.title }}</a></strong><br />
		<span class="minor">
		On list: <a href="{% url 'todo-incomplete_tasks' f.list.id f.list.slug %}">{{ f.list }}</a><br />
		Assigned to: {{ f.assigned_to }} (created by: {{ f.created_by }})<br />
		Complete: {{ f.completed|yesno:"Yes,No" }}
		</span>
	</p>
	{% endfor %}
	</div>
	{% else %}
	<h2> No results to show, sorry.</h2>
	{% endif %}
{% endif %}
{% endblock %}

templates/todo/view_list.html
{% extends "todo/base.html" %}
{% block title %}Todo List: {{ list.name }}{% endblock %}
{% block top-content %}
{% if perms.todo.add_list %}
<a class="btn btn-default" href="/todo/">To-Do Home</a>
<div class="container">
	{% ifequal list_slug "mine" %}
		<h1>Tasks assigned to {{ request.user }}</h1>
	{% else %}
	{% ifequal auth_ok 1 %}
		<h1>Tasks filed under "{{ list.name }}"</h1>
		<p>This list belongs to group {{ list.group }}</p>
	{% endifequal %}
	{% endifequal %}
	{% if messages %}
	<ul class="messages">
		{% for message in messages %}
		<li>{{ message }}</li>
		{% endfor %}
	</ul>
	{% endif %}
	{% ifequal auth_ok 1 %}
	<form class="form-horizontal" action="" method="POST">
	{% csrf_token %}
	
	{# Only show task adder if viewing a proper list #}
	{% ifnotequal list_slug "mine" %}
	<h2 style="margin-bottom:0px;" id="slideToggle" >&rarr; Click to add task &larr;</h2>
	<div id="AddTask">
		<table class="table table-striped table-hover table-todo" border="0" cellspacing="5" cellpadding="5">
			<tr>
				<td>{{ form.title.errors }}</td>
				<td>{{ form.due_date.errors }}</td>
			</tr>
			<tr>
				<td><label for="id_title">Task:</label> {{ form.title }}</td>
				<td><label for="id_due_date">Due date:</label> {{ form.due_date }}</td>
				<td><label for="id_assigned">Assign to:</label> {{ form.assigned_to }}</td>
				<td><label for="id_notify">Notify*:</label> <input type="checkbox" checked="checked" name="notify" value="1" id="notify"></td>
 			</tr>
			<tr>
				<td colspan="5"><label for="id_note">Note:</label> {{ form.note }}
					<p class="minor">*Email notifications will only be sent if task is assigned to someone besides yourself.</p>
				</td>
 			</tr>
		</table>
		<input type="hidden" name="priority" value="999" id="id_priority">
		<input type="hidden" name="created_by" value="{{ request.user.id }}" id="id_created_by">
		<input type="hidden" name="list" value="{{ listid }}" id="id_list">
		<input type="hidden" name="created_date" value="{{ created_date }}" id="id_created_date">
		<p><input type="submit" name="add_task" value="Add task" class="btn btn-default"></p>
	</div>
		{% endifnotequal %}
	{% ifequal view_completed 0  %}
	<h3>Incomplete tasks :: Drag rows to set priorities</h3>
	<table border="0" id="tasktable" class="table table-striped table-hover table-todo">
		<tr>
			<th>Done</th>
			<th>Task</th>
			<th>Created</th>
			<th>Due on</th>
			<th>Owner</th>
			<th>Assigned</th>
			<th>Note</th>
			<th>Comm</th>
			{% ifequal list_slug "mine" %}
			<th>List</th>
			{% endifequal %}
			<th>Del</th> 
		</tr>
		{% for task in task_list %}
			<tr class="{% cycle 'row1' 'row2' %}" id="{{ task.id }}">
				<td><input type="checkbox" name="mark_done" value="{{ task.id }}" id="mark_done_{{ task.id }}">	</td> 
				<td><a href="{% url 'todo-task_detail' task.id %}">{{ task.title|truncatewords:20 }}</a></td> 
				<td>{{ task.created_date|date:"m/d/Y" }}</td> 
				<td>
				{% if task.overdue_status %}<span class="overdue">{% endif %}
					{{ task.due_date|date:"m/d/Y" }}  
				{% if task.overdue_status %}</span>{% endif %}
				</td>
				<td>{{ task.created_by }}</td> 
				<td>{{ task.assigned_to }}</td>
				<td style="text-align:center;">{% if task.note %}&asymp;{% endif %} </td>
				<td style="text-align:center;">{% ifnotequal task.comment_set.all.count 0  %}{{ task.comment_set.all.count }}{% endifnotequal %}
				</td>
				{% ifequal list_slug "mine" %}
				<td><a href="{% url 'todo-incomplete_tasks' task.list.id task.list.slug %}">{{ task.list }}</a></td>	
				{% endifequal %}
				<td><input type="checkbox" name="del_task" value="{{ task.id }}" id="del_task_{{ task.id }}">	</td>
			</tr>
		{% endfor %}
	</table>
	<p><input type="submit" name="mark_tasks_done" value="Update..."  class="btn btn-default"></p>
	<p><a  class="btn btn-info" href="{% url 'todo-completed_tasks' list_id list_slug %}">View completed tasks</a></p>
	{% endifequal %}
	{% ifequal view_completed 1 %}
	<h3>Completed tasks</h3> 
	<table border="0"  id="tasktable" class="table table-striped table-hover table-todo">
		<tr>
			<th>Undo</th>
			<th>Task</th>
			<th>Created</th>
			<th>Completed on</th>
			<th>Note</th>
			<th>Comm</th>
			{% ifequal list_slug "mine" %}
			<th>List</th>
			 {% endifequal %}
			<th>Del</th>
		</tr>
		{% for task in completed_list %}
			<tr class="{% cycle 'row1' 'row2' %}">
				<td><input type="checkbox" name="undo_completed_task" value="{{ task.id }}" id="id_undo_completed_task{{ task.id }}">	</td>
				<td><a href="{% url 'todo-task_detail' task.id %}">{{ task.title|truncatewords:20 }}</a></td> 
				<td>{{ task.created_date|date:"m/d/Y" }}</td> 
				<td>{{ task.completed_date|date:"m/d/Y" }}</td>
				<td style="text-align:center;">{% if task.note %}&asymp;{% endif %} </td>
				<td style="text-align:center;">{% ifnotequal task.comment_set.all.count 0  %}{{ task.comment_set.all.count }}{% endifnotequal %}
				<td><input type="checkbox" name="del_completed_task" value="{{ task.id }}" id="del_completed_task_{{ task.id }}">	</td>
			</tr>
		{% endfor %}
	</table>
	<p><input type="submit" name="deldonetasks" value="Continue..."  class="btn btn-default"></p>
	</form> 
	<p><a  class="btn btn-info" href="{% url 'todo-incomplete_tasks' list_id list_slug %}">View incomplete tasks</a></p>
	{% endifequal %}
	{% ifequal can_del 1 %}
	{% ifnotequal list_slug "mine" %}
		<p><a class="btn btn-danger" href="{% url 'todo-del_list' list_id list_slug %}">Delete this list</a></p>
	{% endifnotequal %}
	{% endifequal %}
	{% endifequal %}
{% endif %}
{% endblock %}
{% block app.scripts %}
<script type="text/javascript">
function order_tasks(data) {
	// The JQuery plugin tableDnD provides a serialize() function which provides the re-ordered 
	// data in a list. We pass that list as an object called "data" to a Django view 
	// to save the re-ordered data into the database.
	$.post("{% url 'todo-reorder_tasks' %}", data, "json");
	return false;
};
$(document).ready(function() {
	// Initialise the task table for drag/drop re-ordering
	$("#tasktable").tableDnD();
	$('#tasktable').tableDnD({
		onDrop: function(table, row) {
			order_tasks($.tableDnD.serialize());
		}
	});
	// Initially hide the Add Task form
	$('#AddTask').hide();
	// toggle slide to show the Add Task form when link clicked
	$('#slideToggle').click(function(){
		$(this).siblings('#AddTask').slideToggle();
	});
});
</script>
</div>
{% endblock %}

templates/todo/view_task.html
{% extends "todo/base.html" %}
{% block title %}Task: {{ task.title }}{% endblock %}
{% block top-content %}
{% if perms.todo.add_list %}
<a class="btn btn-default" href="/todo/">To-Do Home</a>
<div class="container">
{% if messages %}
<ul class="messages">
	{% for message in messages %}
	<li>{{ message }}</li>
	{% endfor %}
</ul>
{% endif %}
{% ifequal auth_ok 1 %}
<h2>{{ task }}</h2>
<form action="" method="POST">
{% csrf_token %}	
<p id="slideToggle" ><strong>&rarr; Click to edit details &larr;</strong></p>
<p><strong>In list:</strong> <a href="{% url 'todo-incomplete_tasks' task.list.id task.list.slug %}" class="showlink">{{ task.list }}</a><br />
<strong>Assigned to:</strong> {{ task.assigned_to.first_name }} {{ task.assigned_to.last_name }}<br />
<strong>Created by:</strong> {{ task.created_by.first_name }} {{ task.created_by.last_name }}<br />
<strong>Due date:</strong>  {{ task.due_date }}<br />
<strong>Completed:</strong> {{ form.completed }}<br />
</p>
{% if task.note %}
<div class="task_note"><strong>Note:</strong> {{ task.note|safe|urlize|linebreaks }}</div>
{% endif %}
<div id="TaskEdit">
<h3>Edit Task</h3>
<table class="table table-striped table-hover table-todo">
	{{ form.management_form }}
	{{ form.id }}
<tr>	
	<td>Title:</td>
	<td>{{ form.title }}  </td>
</tr>
<tr>	
	<td>List:</td>
	<td>{{ form.list }}  </td>
</tr>
<tr>	
	<td>Due:</td>
	<td>{{ form.due_date }}  </td>
</tr>
<tr>	
	<td>Assigned to:</td>
	<td>{{ form.assigned_to }}  </td>
</tr>
<tr>	
	<td valign="top">Note:</td>
	<td>{{ form.note }}  </td>
</tr>
<tr>	
	<td>Priority:</td>
	<td>{{ form.priority }}  </td>
</tr>
</table>
<p><input type="submit" class="btn btn-default" name="edit_task" value="Edit task"></p>
</div>
<hr />
<h3>Add comment</h3>
	<textarea class="form-control" rows="3" name="comment-body"></textarea>
	<p><input class="btn btn-default"type="submit" value="Submit"></p>
</form>
<h3>Comments on this task</h3>	
<div class="task_comments">
{% for comment in comment_list %}
	<p><strong>{{ comment.author.first_name }} {{ comment.author.last_name }}, {{ comment.date|date:"F d Y P" }}</strong> </p>
	{{ comment.body|safe|urlize|linebreaks }}
{% empty %}
<p>No Comments</p>
{% endfor %}
</div>
{% endifequal %}
</div>
{% endif %}
{% endblock %}
{% block app.scripts %}
<script type="text/javascript">
$(document).ready(function() {
	// Initially hide the TaskEdit form
	$('#TaskEdit').hide();
	
	// toggle slide to show the Add Task form when link clicked
	$('#slideToggle').click(function(){
		$(this).siblings('#TaskEdit').slideToggle();
	});
});
</script>
{% endblock %}