somesmart/urls.py
from django.conf.urls.defaults import *
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, ListView, UpdateView, CreateView, DeleteView, TemplateView
from django.db.models import Count
from sssd.somesmart.models import *
from sssd.somesmart.views import *

urlpatterns = patterns('',
	#home page
	url(r'^$',
		ListView.as_view(
			queryset=Review.objects.select_related().annotate(reviewed=Count('id')).order_by('-finished')[:10],
			context_object_name='recent_reads',
			template_name='somesmart/base_index.html')),
	#about page
	url(r'^about/$', TemplateView.as_view(template_name = 'somesmart/base_about.html'), name='about-page'),
	#book details
	url(r'^book/(?P<pk>\d+)/', BookView.as_view(), name='book-view'),
	url(r'^author/(?P<pk>\d+)/', AuthorView.as_view(), name='author-view'),
	url(r'^my-books/$', TemplateView.as_view(template_name = 'somesmart/base_mybooks.html'), name='my-books'),
	#charts
	url(r'^charts/$', GlobalStats.as_view(), name='charts'),
	url(r'^charts/(?P<chart>[-\w]+)/(?P<option>[\s\w\d]+)$', ChartGenerate.as_view(), name='chart-generate'),
	url(r'^stats/global/$', 'sssd.somesmart.views.get_global_stats', name='global-stats'),
	#quote pages
	url(r'^quote/list/$', QuoteList.as_view(), name='quote-list'),
	url(r'^quote/type/(?P<type>\d+)/$',QuoteTypeList.as_view(), name='quote-type-list'),
	url(r'^quote/author/(?P<author>\d+)/',QuoteAuthorList.as_view(), name='quote-author-list'),
	url(r'^quote/book/(?P<book>\d+)/',QuoteBookList.as_view(), name='quote-book-list'),
	url(r'^quote/(?P<pk>\d+)/', QuoteView.as_view(), name='quote-view'),
	url(r'^quote/random/$', 'sssd.somesmart.views.get_random_quote', name='random-quote'),
	#read details
	url(r'^review/(?P<pk>\d+)/', ReviewView.as_view(), name='review-view'),
	url(r'^review/book/(?P<pk>\d+)/', ReviewByBook.as_view(), name='review-by-book'),
	url(r'^review/list/$', ReviewList.as_view(), name='review-list'),
	url(r'^review/list/(?P<genre>[-\w]+)/$', ReviewGenreList.as_view(), name='review-genre-list'),
	#shelf details
	url(r'^shelf/(?P<pk>\d+)/', ShelfView.as_view(), name='shelf-view'),
	#automplete all pass to the same view
	url(r'autocomplete/$','sssd.somesmart.views.autocomplete', name='autocomplete'),
	url(r'gr/current/$', 'sssd.somesmart.views.get_gr_current', name='get-gr-current'),
	#lists
	url(r'^list/(?P<pk>\d+)/', ListDetailView.as_view(), name='list-view'),
	url(r'^list/$', ListSummary.as_view(), name='list-summary'),
	url(r'^add/list/$', login_required(ListCreateView.as_view(template_name='somesmart/base_list_create.html')), name='list-add'),
	url(r'^add/list/(?P<list>\d+)/item/(?P<book>\d+)/$', 'sssd.somesmart.views.add_list_item'),
	url(r'^copy/list/(?P<list>\d+)/$', 'sssd.somesmart.views.copy_list', name='list-copy'),
	url(r'^edit/list/(?P<pk>\d+)/$', login_required(ListUpdate.as_view(template_name='somesmart/base_list_update.html'))),
	url(r'^delete/list/item/(?P<pk>\d+)/$', 'sssd.somesmart.views.delete_list_item'),
	url(r'^delete/list/(?P<pk>\d+)/$', 'sssd.somesmart.views.delete_list'),
	#favorites
	url(r'^favorites/$', FavoriteList.as_view(), name='favorite-list'),
	url(r'^favorites/(?P<genre>[-\w]+)/$', FavoriteGenreList.as_view(), name='favorite-genre-list'),
	#tags
	url(r'^tags/current/$', 'sssd.somesmart.views.current_tags', name='current-tags'),
	url(r'^tags/book/(?P<book>\d+)/$', 'sssd.somesmart.views.book_tags', name='book-tags'),
	url(r'^tags/book/(?P<book>\d+)/save/$', 'sssd.somesmart.views.save_tags', name='save-tags'),
	url(r'^tags/book/(?P<book>\d+)/related/$', 'sssd.somesmart.views.get_related', name='related-books'),
	url(r'^tags/search/(?P<tag>[\s\w]+)/$',TagListView.as_view(), name='search-tags'),
	url(r'^tags/cloud/(?P<min_count>\d+)/$', 'sssd.somesmart.views.get_cloud', name='tag-cloud'),
	#the blog
	url(r'^blog/', include('zinnia.urls')),
	url(r'^blog/tags/', include('zinnia.urls.tags')),
	url(r'^blog/feeds/', include('zinnia.urls.feeds')),
	url(r'^blog/authors/', include('zinnia.urls.authors')),
	url(r'^blog/categories/', include('zinnia.urls.categories')),
	url(r'^blog/archives/', include('zinnia.urls.archives')),
	url(r'^blog/', include('zinnia.urls.entries')),
	url(r'^blog/', include('zinnia.urls.shortlink')),
	url(r'^blog/', include('zinnia.urls.quick_entry')),
	url(r'^comments/', include('django.contrib.comments.urls')),
	(r'^contact/', include('contact_form.urls')),
	url(r'noresults/', TemplateView.as_view(template_name = 'somesmart/base_noresults.html'), name='no-results'),
	#legacy urls
	url(r'^books/bookinfo\.php$', 'sssd.somesmart.views.bookinfo_php', name='bookinfo-php'),
	url(r'^bookinfo\.php$', 'sssd.somesmart.views.bookinfo_php', name='bookinfo-php'),
	url(r'^reviews/$', 'sssd.somesmart.views.bookinfo_php', name='review-old'),
	#malformatted archive links go to the homepage
	url(r'^(?P<year>\d{4})/(?P<month>\d{2})/', ListView.as_view(
			queryset=Review.objects.select_related().annotate(reviewed=Count('id')).order_by('-finished')[:10],
			context_object_name='recent_reads',
			template_name='somesmart/base_index.html')),
	url(r'^(?P<year>\d+)/(?P<slug>[-\w]+)/', 'sssd.somesmart.views.zinnia_entry_detail', name='custom-zinnia'),
	url(r'^feeds/$', 'sssd.somesmart.views.zinnia_latest_feeds', name='custom-zinnia-latest'),
	url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'somesmart/base_login.html'}, name='account-login'),
	url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'template_name': 'somesmart/base_logged_out.html'}, name='account-logout'),
	url(r'^todo/', include('todo.urls')),
)

urls.py
from django.conf.urls.defaults import *
from django.views.generic import DetailView, ListView, UpdateView, CreateView, DeleteView
from django.contrib import admin
from sssd.somesmart.models import *
from sssd.somesmart.views import *

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^admin/', include(admin.site.urls)),
	url(r'^adventure/', include('sssd.adventure.urls')),
	url(r'^lotr/', include('sssd.lotr.urls')),
	url(r'^', include('sssd.somesmart.urls')),
)

somesmart/models.py
from django.db import models
from django.core.urlresolvers import reverse
import datetime
from django.contrib.auth.models import User
import os
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill, Adjust
import tagging

class IntegerRangeField(models.IntegerField):
	def __init__(self, verbose_name=None, name=None, min_value=None, max_value=None, **kwargs):
		self.min_value, self.max_value = min_value, max_value
		models.IntegerField.__init__(self, verbose_name, name, **kwargs)
	def formfield(self, **kwargs):
		defaults = {'min_value': self.min_value, 'max_value':self.max_value}
		defaults.update(kwargs)
		return super(IntegerRangeField, self).formfield(**defaults)

class Genre(models.Model):
	name = models.TextField(max_length=100)
	slug = models.SlugField()

	def __unicode__(self):
		return self.name

	def save(self, *args, **kwargs):
		if not self.id:
			# Newly created object, so set slug
			self.slug = slugify(self.name)

		super(Genre, self).save(*args, **kwargs)

class Author(models.Model):
	last_name = models.CharField(max_length=200)
	first_name = models.CharField(max_length=200)
	birth_date = models.DateTimeField(null=True, default=None, blank=True)
	death_date = models.DateTimeField(null=True, default=None, blank=True)
	pen_name = models.BooleanField()
	parent_author = models.ForeignKey('self', blank=True, default=None, null=True, help_text='The real name of a pen name')

	def __unicode__(self):
		return u"%s %s" % (self.first_name, self.last_name)	

class Book(models.Model):
	title = models.CharField(max_length=200)
	author = models.ForeignKey(Author)
	original_publication = models.DateTimeField()
	synopsis = models.TextField(blank=True)
	reading_age = models.IntegerField()
	content_advisory = models.TextField(blank=True)
	genre = models.ForeignKey(Genre)

	def __unicode__(self):
		return self.title

tagging.register(Book)

class Edition(models.Model):
	def get_image_path(instance, filename):
		return os.path.join('photos/book', str(instance.book.id), filename)

	FORMAT = (
		(1, 'Hardcover'),
		(2, 'Paperback'),
		(3, 'Digital'),
		(4, 'Audio'),
	)

	book = models.ForeignKey(Book)
	isbn = models.CharField(max_length=20)
	published = models.DateTimeField()
	pages = models.IntegerField()
	format = models.IntegerField(choices=FORMAT)
	cover = models.ImageField(upload_to=get_image_path, blank=True)
	cover_thumbnail = ImageSpecField([Adjust(contrast=1.2, sharpness=1.1), ResizeToFill(50, 50)], image_field='cover', format='JPEG', options={'quality': 90})
	cover_large = ImageSpecField([Adjust(contrast=1.2, sharpness=1.1), ResizeToFill(333, 500)], image_field='cover', format='JPEG', options={'quality': 90})
	cover_md = ImageSpecField([Adjust(contrast=1.2, sharpness=1.1), ResizeToFill(100, 170)], image_field='cover', format='JPEG', options={'quality': 90})

	def __unicode__(self):
		return u"%s - %s" % (self.book.title, self.get_format_display())

class Review(models.Model):
	reader = models.ForeignKey(User, related_name="+")
	started = models.DateTimeField()
	finished = models.DateTimeField()
	edition = models.ForeignKey(Edition)
	critique = models.TextField(blank=True)
	one_sentence = models.CharField(max_length=300, null=True, default=None, blank=True)
	recommend = models.BooleanField()

	def __unicode__(self):
		return self.one_sentence

#I should consider doing this as a tagging module of some sort. The advantage of having it being "keywords" like this
#is we can also attribute the tag/keyword to the user.
class Keyword(models.Model):
	book = models.ForeignKey(Book)
	reader = models.ForeignKey(User, related_name='+')
	keyword = models.CharField(max_length=100)

class QuoteType(models.Model):
	name = models.CharField(max_length=50)
	def __unicode__(self):
		return self.name

class Quote(models.Model):
	edition = models.ForeignKey(Edition)
	reader = models.ForeignKey(User, related_name='+')
	quote_type = models.ForeignKey(QuoteType)
	quote = models.TextField()
	page = models.IntegerField()

	def __unicode__(self):
		return self.quote

class Note(models.Model):
	quote = models.ForeignKey(Quote)
	reader = models.ForeignKey(User, related_name='+')
	note = models.TextField()

	def __unicode__(self):
		return self.note

class Radar(models.Model):
	book = models.ForeignKey(Book)
	maturity = models.IntegerField()
	violence = models.IntegerField()
	action = models.IntegerField()
	epic = models.IntegerField()
	world = models.IntegerField()
	realism = models.IntegerField()
	modernity = models.IntegerField()
	humor = models.IntegerField()

class Shelf(models.Model):
	reader = models.ForeignKey(User, related_name='+')
	name = models.CharField(max_length=100)
	private = models.BooleanField()

	def __unicode__(self):
		return self.name

class ShelfDetail(models.Model):
	shelf = models.ForeignKey(Shelf)
	book = models.ForeignKey(Book)

#will probably be able to do this just by pulling in the current status from goodreads
class Currently(models.Model):
	edition = models.ForeignKey(Edition)
	reader = models.ForeignKey(User, related_name='+')
	page = models.IntegerField()

class Favorite(models.Model):
	book = models.ForeignKey(Book)
	user = models.ForeignKey(User, related_name='+')
	rank = models.IntegerField()
	comment = models.TextField()

# ************************************************************** #
# ************************ list data *************************** #
# ************************************************************** #

class List(models.Model):
	list_name = models.CharField(max_length=200)
	list_descr = models.CharField(max_length=200)
	user = models.ForeignKey(User, related_name="+") #this is the person who created it, and it will always be here
	def __unicode__(self):
		return self.list_name
		return u"%s - %s" % (self.list_name, self.list_descr)
	def get_absolute_url(self):
		return "/list/%i/" % self.id
	def get_edit_url(self):
		return "/edit/list/%i/" % self.id
	def get_delete_url(self):
		return "/delete/list/%i/" % self.id	
	def get_add_url(self):
		return "/add/list/"

class ListDetail(models.Model):
	list = models.ForeignKey(List, related_name="list_details")
	book = models.ForeignKey(Book)

# ************************************************************** #
# *********************** series data ************************** #
# ************************************************************** #

class Series(models.Model):
	name = models.CharField(max_length=200)
	count = models.IntegerField()

	def __unicode__(self):
		return self.name

class SeriesDetail(models.Model):
	series = models.ForeignKey(Series)
	book = models.ForeignKey(Book)
	sequence = models.IntegerField()

	def __unicode__(self):
		return u"%s - %s, %s of %s" % (self.series, self.book, self.sequence, self.series.count)

somesmart/forms.py
from django import forms
from django.forms import ModelForm, Textarea
from django.forms.models import inlineformset_factory
from sssd.somesmart.models import *

# ****************************************************************** #
# ********************* course related forms *********************** #
# ****************************************************************** #

class ListForm(ModelForm):
	list_descr = forms.CharField(widget=forms.TextInput(attrs={'size':'60'}))
		
	class Meta:
		model = List
		exclude = ('user')

	def __init__(self, *args, **kwargs):
		super(ListForm, self).__init__(*args, **kwargs)
		self.fields['list_name'].label = "List Name"
		self.fields['list_descr'].label = "List Description"

class ListDetailForm(ModelForm):
	class Meta:
		model = ListDetail 

ListDetailFormSet = inlineformset_factory(List, ListDetail, form=ListDetailForm)

templates/somesmart/base_book.html
{% extends "somesmart/base.html" %}
{% load tagging_tags %}
{% load admin_urls %}
{% block title %}{{ book.title }}{% endblock title %}
{% block content %}
	<div>
		<h2>{{ book.title }}<br><small>by <a href="{% url 'author-view' book.author.id %}">{{ book.author }}</a></small></span></h2>
	</div>
	{% if book.synopsis %}
	<h4>Synopsis</h4>
	<div class="row">
		<p class="col-md-5 alert alert-info">This synopsis will contain spoilers!</p>
	</div>
	<div class="review">
		{{ book.synopsis|safe }}
	</div>
	{% endif %}
	<h4>Reviews</h4>
	<dl>
	{% for edition in book.edition_set.all %}
	{% for review in edition.review_set.all %}
			<dt><a href="{% url 'review-view' review.id %}{{ review.edition.book.title|slugify }}">{{ review.edition }}</a>{% if review.recommend %} <i class="glyphicon glyphicon-thumbs-up"></i>{% else %} <i class="glyphicon glyphicon-thumbs-down"></i>{% endif %}</dt>
			<dd>{% if review.one_sentence %}{{ review.one_sentence|safe }}{% else %}{{ review.critique|truncatewords_html:30|safe }}{% endif %} - {{ review.finished|date }}</dd>
	{% endfor %}
	{% endfor %}
	</dl>
	<h4>Quotes</h4>
	{% for edition in book.edition_set.all %}
		{% for quote in edition.quote_set.all %}
			{% include "somesmart/include_quote.html" %}
		{% endfor %}
	{% endfor %}
	{% if request.user.id == 2 %}
		<a class="btn btn-default pull-right" href="{% url 'admin:somesmart_book_change' book.id %}">Edit this book</a>
	{% endif %}
{% endblock content %}
{% block top-right-content %}{% endblock %}
{% block right-content %}
	{% include "somesmart/include_book_data.html" %}
	{% include "somesmart/include_recent_posts.html" %}
	{% include "somesmart/include_book_tags.html" %}
	{% if series %}
		{% include "somesmart/include_series_data.html" %}
	{% endif %}
	<div class="row">
		<h4 class="well well-sm">Related Books</h4>
		<div id="related-books"></div>
	</div>
{% endblock %}
{% block app.scripts %}
<script type="text/javascript" src="{{ MEDIA_URL }}js/tagmanager/bootstrap-tagmanager.js"></script>
<script>
function get_related(book){
	$.ajax({
		type: "GET",
		url: '{% url "related-books" book.id %}',
		success: function(data) {
			$('#related-books').append(data);
		}
	});
 }
 $(function() {
	jQuery(".tagManager").tagsManager({
		prefilled: [{% tags_for_object book as prefilled_tags %}{% for tag in prefilled_tags %}"{{ tag.name }}"{% if not forloop.last %},{% endif %}{% endfor %}],
		preventSubmitOnEnter: true,
		typeahead: true,
		typeaheadAjaxSource: '{% url "current-tags" %}', 
		typeaheadAjaxPolling: false
	});
	{% if request.user.id == 2 %}
	$('.save-tags').click(function() {
		var new_tags = $('input[name=hidden-tagsjax]').val();
		$.ajax({
			url: '{% url "save-tags" book.id %}',
			type: 'POST',
			data: {
			new_tags: new_tags,
			csrfmiddlewaretoken: '{{ csrf_token }}'
			},
			success:function (data) {
			if (data == '1')
			{
				$("#tags-status")
				.addClass("success")
				.html("<div class='alert alert-success'>Your keywords have been saved. <a href='#'' class='close' data-dismiss='alert'>×</a></div>").fadeIn('slow');
			}
			else
			{
				$("#tags-status").addClass("error").html("Error, data could not be saved. Invalid keywords: " + data + " <a href='#'' class='close' data-dismiss='alert'>×</a>").fadeIn('slow');
			}
			}
		});
	});
	{% endif %}
	get_related();
});
</script>
{% endblock %}

templates/somesmart/base_favorite_list.html
{% extends "somesmart/base.html" %}
{% block title %}Favorite Books{% endblock title %}
{% block top-content %}{% endblock %}
{% block content %}
<p class="well well-sm">While you can find various books that I enjoy and recommend from the blog and reviews on the site, searching through all of that can be rather daunting. This page will be an up to date list of my favorite books to read and to recommend by genre. This may also include books I don't yet have a database or blog entry on, but still want to share with others. If you've found that you've read all the books listed in a genre, the rest of the site may be for you!</p>
	{% if genre_list %}
		<ul class="list-unstyled list-inline">
		{% for genre in genre_list %}
			<li><a class="btn btn-default btn-sm" href="{% url 'favorite-genre-list' genre.book__genre__slug %}">{{ genre.book__genre__name }}</a></li>
		{% endfor %}
		</ul>
	{% endif %}
	{% if favorite_list %}
		{% for favorite in favorite_list %}
		<div class="media">
			<a class="pull-left" href="#">
				{% for edition in favorite.book.edition_set.all %}
					{% if forloop.first %}<center>{% if edition.cover %}<img class="media-object" src="{{ edition.cover_md.url }}" width="100px">{% else %}<img data-src="holder.js/100x150/auto" width="100px">{% endif %}</center>{% endif %}
				{% endfor %}
			</a>
			<div class="media-body">
				<h4 class="media-heading"><a href="{% url 'book-view' favorite.book.id %}{{ favorite.book.title|slugify }}">{{ favorite.book.title }}</a></h4>
				{{ favorite.comment|safe }}
			</div>
		</div>
		{% endfor %}
	{% endif %}
	{% include "somesmart/include_pagination.html" %}
{% endblock content %}
{% block app.scripts %}
	<script type="text/javascript" src="{{ MEDIA_URL }}js/holder/holder.js"></script>
{% endblock %}

templates/somesmart/base_index.html
{% extends "somesmart/base.html" %}
{% load zinnia_tags %}
{% block title %} Welcome to some smart, some don't {% endblock title %}
{% block content %}
	{% get_recent_entries 10 "zinnia/home_excerpts.html" %}
	<a class="btn btn-primary pull-right" href="blog/?page=2">More entries &raquo;</a>
{% endblock content %}
{% block right-content %}
<h4 class="well well-sm">Recent Reviews</h4>
{% if recent_reads %}
	<ul class="list-unstyled">
	{% for review in recent_reads %}
		{% if review.reviewed > 0 %}
		<li><a href="{% url 'review-view' review.id %}{{ review.edition.book.title|slugify }}">{{ review.edition.book.title }}</a> - {{ review.finished|date }}{% if review.recommend %} <i class="glyphicon glyphicon-thumbs-up" title="Recommended!"></i>{% else %} <i class="glyphicon glyphicon-thumbs-down" title="Not Recommended"></i>{% endif %}</li>
		{% endif %}
	{% endfor %}
	</ul>
{% else %}
	<p>No reviews.</p>
{% endif %}
<h4 class="well well-sm">Most Used Tags</h4>
<div id="tag-cloud"></div>
<a href="{% url 'zinnia_entry_latest_feed' %}" class="btn btn-default">RSS Feed</a>
<a href='http://cloud.feedly.com/#subscription%2Ffeed%2Fhttp%3A%2F%2Fsomesmart.com%2Fblog%2Ffeeds%2Flatest%2F' class="btn btn-default" target='blank'>Feedly</a>
{% endblock %}
{% block app.scripts %}
<script>
function get_cloud(){
	$.ajax({
		type: "GET",
		url: '{% url "tag-cloud" 4 %}',
		success: function(data) {
			$('#tag-cloud').append(data);
		}
	});
}
$(function() {
	get_cloud();
});
</script>
{% endblock %}

templates/somesmart/base_review.html
{% extends "somesmart/base.html" %}
{% load tagging_tags %}
{% load somesmart_extras %}
{% load admin_urls %}
{% block title %}{{ review.edition.book.title }} Review{% endblock title %}
{% block content %}
	<div>
		<h2>{{ review.edition.book.title }}<br><small>by <a href="{% url 'author-view' review.edition.book.author.id %}">{{ review.edition.book.author }}</a></small></h2>
	</div>
	<div class="pull-right">
	{% with review.one_sentence|length|add:-1 as review_len %}
		<a href="https://twitter.com/share" class="twitter-share-button" data-related="jasoncosta" data-lang="en" data-size="small" data-count="horizontal" data-text="{% if review_len > 117 %}{{ review.one_sentence|safe|truncchar:115 }}...{% else %}{{ review.one_sentence|safe|truncchar:review_len }}{% endif %}">Tweet</a>
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
	{% endwith %}
	</div>
	<h4>A Review by {{ review.reader }} <small>finished {{ review.finished|date }}</small></h4>
	{% if review.one_sentence %}
		<p><strong>In one sentence:</strong> {{ review.one_sentence|safe }}</p>
	{% endif %}
	<div class="row">
		<p class="col-md-5 alert alert-info">This review will contain spoilers!</p>
	</div>
	<p><strong>In many sentences:</strong></p>
	<div class="review">{{ review.critique|safe }}</div>
	{% for quote in review.edition.quote_set.all %}
		<h4>{{ quote.quote_type }}{% if quote.quote_type.id == 1 %} Quote{% endif %}</h4>
		{% include "somesmart/include_quote.html" %}
	{% endfor %}
	{% if request.user.id == review.reader.id %}
		<a class="btn btn-default pull-right" href="{% url 'admin:somesmart_review_change' review.id %}">Edit this review</a>
	{% endif %}
{% endblock content %}
{% block top-right-content %}{% endblock %}
{% block right-content %}
{% with review.edition.book as book %}
	{% include "somesmart/include_book_data.html" %}
	{% include "somesmart/include_recent_posts.html" %}
	{% include "somesmart/include_book_tags.html" %}
{% endwith %}
<div class="row">
	<h4 class="well well-sm">Related Books</h4>
	<div id="related-books"></div>
</div>
{% endblock %}
{% block app.scripts %}
<script type="text/javascript" src="{{ MEDIA_URL }}js/tagmanager/bootstrap-tagmanager.js"></script>
<script>
function get_related(book){
	$.ajax({
		type: "GET",
		url: '{% url "related-books" review.edition.book.id %}',
		success: function(data) {
			$('#related-books').append(data);
		}
	});
}
$(function() {
	jQuery(".tagManager").tagsManager({
		prefilled: [{% tags_for_object review.edition.book as prefilled_tags %}{% for tag in prefilled_tags %}"{{ tag.name }}"{% if not forloop.last %},{% endif %}{% endfor %}],
		preventSubmitOnEnter: true,
		typeahead: true,
		typeaheadAjaxSource: '{% url "current-tags" %}', 
		typeaheadAjaxPolling: false
	});
	{% if request.user.id == 2 %}
	$('.save-tags').click(function() {
		var new_tags = $('input[name=hidden-tagsjax]').val();
		$.ajax({
			url: '{% url "save-tags" review.edition.book.id %}',
			type: 'POST',
			data: {
			new_tags: new_tags,
			csrfmiddlewaretoken: '{{ csrf_token }}'
			},
			success:function (data) {
			if (data == '1')
			{
				$("#tags-status")
				.addClass("success")
				.html("<div class='alert alert-success'>Your keywords have been saved. <a href='#'' class='close' data-dismiss='alert'>×</a></div>").fadeIn('slow');
			}
			else
			{
				$("#tags-status").addClass("error").html("Error, data could not be saved. Invalid keywords: " + data + " <a href='#'' class='close' data-dismiss='alert'>×</a>").fadeIn('slow');
			}
			}
		});
	});
	{% endif %}
	get_related();
});
</script>
{% endblock %}

templates/somesmart/base_search_tags.html
{% extends "somesmart/base.html" %}
{% block title %}Tag Search{% endblock title %}
{% block top-content %}
<div class="row">
	<div class="col-md-8 col-lg-offset-2 random-quote"></div>
	<div class="col-md-2"></div>
</div>
<div class="row">
	<div class="col-md-10 col-lg-offset-1">
		<h3>Tag search results</h3>
		{% if book_list %}
			{% for book in book_list %}
				{% if forloop.counter0|divisibleby:"3" %}<div class="row">{% endif %}
					<div class="col-md-4">
						<div class="panel panel-default">
							<div class="panel-heading">
								<h5><center><a href="{% url 'book-view' book.object_id %}{{ book.object.title|slugify }}">{{ book }}</a></center></h5>
							</div>
							{% for edition in book.object.edition_set.all %}
								{% if forloop.first %}
									<div class="panel-body">
										<center>{% if edition.cover %}<img src="{{ edition.cover.url }}" height="300px">{% else %}<img data-src="holder.js/200x300/auto" height="300px">{% endif %}</center>
									</div>
								{% endif %}
							{% endfor %}
						</div>
					</div>
				{% if forloop.last or forloop.counter|divisibleby:"3" %}</div>{% endif %}
			{% endfor %}
		{% else %}
			<p>No books found.</p>
		{% endif %}
	</div>
</div>
{% include "somesmart/include_pagination.html" %}
{% endblock %}
{% block top-right-content %}{% endblock top-right-content %}
{% block app.scripts %}
<script src="{{ MEDIA_URL }}js/holder/holder.js"></script>
{% endblock %}

templates/somesmart/base_shelf.html
{% extends "somesmart/base.html" %}
{% block title %}{{ shelf.name }}{% endblock title %}
{% block content %}
   <div class="page-header">
    <h1>{{ shelf.name }} <small>{{ shelf.reader }}</small></h1>
  </div>
{% endblock content %}

templates/somesmart/include_recent_posts.html
{% if book.entry_set.all %}
<div class="row">
	<h4 class="well well-sm">Recent Blog Posts</h4>
</div>
	<ul class="list-unstyled">
		{% for entry in book.entry_set.all %}
			<li><a href="{{ entry.get_absolute_url }}"><i class='glyphicon glyphicon-minus'></i> {{ entry.title }}</a></li>
		{% endfor %}
	</ul>
{% endif %}